export const ghana = {
  name: "Ghana",
  mapID: "ghana",
  lat: 8.059229627200192,
  long: -1.0546875000000002,
  zoom: 7,
  minzoom: 7,
  currentLayer: "2",
  currentLegend: "0",
  distNames: null,
  /* 
    you can add as many layers for each indicator. 
    do maintain the same structure for all. 
    */
  layers: [
    {
      name: "Country Border",
      carto_tableName: "gha_adm0",
      carto_layer: null /* we will insert carto's layer object here */,
      carto_style: `#layer {
          polygon-fill: #826dba;
          polygon-opacity: 0;
        }
        #layer::outline {
          line-width: 1.75;
          line-color: #000000;
          line-opacity: 1;
        }`,
      visible: true,
      filters: [],
    },
    {
      name: "1x1km area",
      carto_tableName: "gha_class",
      carto_source: null,
      carto_layer: null /* we will insert carto's layer object here */,
      carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 0;line-color: #ffffff;line-opacity: 0;}`,
      visible: false,
      accessCounter: new Set(null),
      washCounter: new Set(null),
      socioCounter: new Set(null),
      healthCounter: new Set(null),
      filters: [
        {
          name: "Rural Typology",
          unit: "",
          type: "categorical",
          column_name: "classes",
          subcategory: "accessibility",
          value: [
            {
              name: "Rural Remote",
              value: 1,
              checked: true,
            },
            {
              name: "Rural On-road",
              value: 2,
              checked: true,
            },
            {
              name: "Rural Mixed",
              value: 3,
              checked: true,
            },
            {
              name: "Urban",
              value: 4,
              checked: true,
            },
          ] /* declaure col values that should be filtered on */,
        },
        // {
        //   name: "Population Estimate",
        //   unit: "people",
        //   type: "range",
        //   column_name: "pop",
        //   min: 0,
        //   max: 24402,
        //   value: [0, 24402],
        //   subcategory: "socioeconomic",
        // },
        // {
        //   name: "Travel Time to Cities",
        //   unit: "min.",
        //   type: "range",
        //   column_name: "timecities",
        //   min: 0,
        //   max: 610,
        //   value: [0, 610],
        //   subcategory: "accessibility",
        // },
        // {
        //   name: "Distance to Roads",
        //   unit: "km.",
        //   type: "range",
        //   column_name: "dr",
        //   min: 0.1,
        //   max: 39.7,
        //   value: [0.1, 39.7],
        //   subcategory: "accessibility",
        // },
        // {
        //   name: "Distance to Towns",
        //   unit: "km.",
        //   type: "range",
        //   column_name: "dt",
        //   min: 0,
        //   max: 77.4,
        //   value: [0, 77.4],
        //   subcategory: "accessibility",
        // },
      ],
    },
    {
      name: "5x5km area",
      carto_tableName: "gha_multivariable_pixel",
      carto_source: null,
      carto_layer: null,
      carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 0;line-color: #ffffff;line-opacity: 0;}`,
      visible: true,
      accessCounter: new Set(null),
      washCounter: new Set(null),
      socioCounter: new Set(null),
      healthCounter: new Set(null),
      filters: [
        {
          name: "Rural Typology",
          unit: "",
          type: "categorical",
          column_name: "classes",
          subcategory: "accessibility",
          value: [
            {
              name: "Rural Remote",
              value: 1,
              checked: true,
            },
            {
              name: "Rural On-road",
              value: 2,
              checked: true,
            },
            {
              name: "Rural Mixed",
              value: 3,
              checked: true,
            },
            {
              name: "Urban",
              value: 4,
              checked: true,
            },
          ] /* declaure col values that should be filtered on */,
        },
        {
          name: "Population Estimate",
          unit: "people",
          type: "range_non_linear",
          column_name: "pop",
          min: 0,
          max: 70, //we want 7 breaks not counting start value of 0.
          value: [0, 70], //slider range will be from 0-70, which we will scale to
          scaledMin: 0,
          scaledMax: 442720,
          scaledValue: [0, 442720], //the actual min/max of column
          subcategory: "socioeconomic",
          // define 7+1 non linear marks here, note that value goes from 0-70 only
          marks: [
            {
              value: 0,
              scaledValue: 0,
              label: "0",
            },
            {
              value: 10,
              scaledValue: 100,
              label: "100",
            },
            {
              value: 20,
              scaledValue: 500,
              label: "500",
            },
            {
              value: 30,
              scaledValue: 1000,
              label: "1K",
            },
            {
              value: 40,
              scaledValue: 5000,
              label: "5K",
            },
            {
              value: 50,
              scaledValue: 50000,
              label: "50K",
            },
            {
              value: 60,
              scaledValue: 100000,
              label: "100K",
            },
            {
              value: 70,
              scaledValue: 500000,
              label: "500K",
            },
          ],
        },
        {
          name: "Population Practicing Open Defecation",
          unit: "%",
          type: "range",
          column_name: "od",
          min: 0,
          max: 99,
          value: [0, 99],
          subcategory: "wash",
        },
        {
          name: "Reliance on Unimproved Sanitation",
          unit: "%",
          type: "range",
          column_name: "s_unimp",
          min: 0,
          max: 90,
          value: [0, 90],
          subcategory: "wash",
        },
        {
          name: "Reliance on Unimproved Drinking Water",
          unit: "%",
          type: "range",
          column_name: "w_unimp",
          min: 0,
          max: 73,
          value: [0, 73],
          subcategory: "wash",
        },
        {
          name: "Travel Time to Cities",
          unit: "min.",
          type: "range",
          column_name: "timecities",
          min: 0,
          max: 592,
          value: [0, 592],
          subcategory: "accessibility",
        },
        {
          name: "Distance to Roads",
          unit: "km.",
          type: "range",
          column_name: "dr",
          min: 0.1,
          max: 37.8,
          value: [0.1, 37.8],
          subcategory: "accessibility",
        },
        {
          name: "Distance to Towns",
          unit: "km.",
          type: "range",
          column_name: "dt",
          min: 0,
          max: 76.2,
          value: [0, 76.2],
          subcategory: "accessibility",
        },
        {
          name: "Diahrrea Prevalence in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "dia",
          min: 2.4,
          max: 6.5,
          value: [2.4, 6.5],
          subcategory: "health",
        },
        {
          name: "Predicted Annual Cholera Incidence",
          unit: "cases/100,000pp",
          type: "range",
          column_name: "cholera",
          min: 0,
          max: 6410.7,
          value: [0, 6410.7],
          subcategory: "health",
        },
        {
          name: "Mortality in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "u5m",
          min: 4.4,
          max: 13.3,
          value: [4.4, 13.3],
          subcategory: "health",
        },
        {
          name: "Women's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_w",
          min: 2,
          max: 10,
          value: [2, 10],
          subcategory: "socioeconomic",
        },
        {
          name: "Men's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_m",
          min: 3,
          max: 11,
          value: [3, 11],
          subcategory: "socioeconomic",
        },
        {
          name: "Rural Remote",
          unit: "%",
          type: "none",
          column_name: "rr",
          subcategory: "accessibility",
        },
        {
          name: "Rural On-road",
          unit: "%",
          type: "none",
          column_name: "rrd",
          subcategory: "accessibility",
        },
        {
          name: "Rural Mixed",
          unit: "%",
          type: "none",
          column_name: "rm",
          subcategory: "accessibility",
        },
        {
          name: "Urban",
          unit: "%",
          type: "none",
          column_name: "u",
          subcategory: "accessibility",
        },
        {
          name: "Region",
          type: "none",
          column_name: "name_1",
          subcategory: "id",
        },
        {
          name: "District",
          type: "none",
          column_name: "name_2",
          subcategory: "id",
        },
      ],
    },
    {
      name: "District",
      carto_tableName: "gha_multivariable_dist_pov",
      carto_source: null,
      carto_layer: null,
      carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 1;line-color: #000000;line-opacity: 1;}`,
      visible: false,
      accessCounter: new Set(null),
      washCounter: new Set(null),
      socioCounter: new Set(null),
      healthCounter: new Set(null),
      filters: [
        {
          name: "Predominant Rural Typology",
          unit: "",
          type: "categorical",
          column_name: "classes",
          value: [
            {
              name: "Predominantly Rural Remote",
              value: 1,
              checked: true,
            },
            {
              name: "Predominantly Rural on-road",
              value: 2,
              checked: true,
            },
            {
              name: "Predominantly Rural Mixed",
              value: 3,
              checked: true,
            },
            {
              name: "Predominantly Urban",
              value: 4,
              checked: true,
            },
          ] /* declaure col values that should be filtered on */,
          subcategory: "accessibility",
        },
        {
          name: "Population Estimate",
          unit: "people",
          type: "range",
          column_name: "pop",
          min: 27942,
          max: 3107236,
          value: [27942, 3107236],
          subcategory: "socioeconomic",
        },
        {
          name: "Average Population Practicing Open Defecation",
          unit: "%",
          type: "range",
          column_name: "od",
          min: 11,
          max: 91,
          value: [11, 91],
          subcategory: "wash",
        },
        {
          name: "Average Reliance on Unimproved Sanitation",
          unit: "%",
          type: "range",
          column_name: "s_unimp",
          min: 1,
          max: 33,
          value: [1, 33],
          subcategory: "wash",
        },
        {
          name: "Average Reliance on Unimproved Drinking Water",
          unit: "%",
          type: "range",
          column_name: "w_unimp",
          min: 0,
          max: 19,
          value: [0, 19],
          subcategory: "wash",
        },
        {
          name: "Average Travel Time to Cities",
          unit: "min.",
          type: "range",
          column_name: "timecities",
          min: 0,
          max: 304,
          value: [0, 304],
          subcategory: "accessibility",
        },
        {
          name: "Average Distance to Roads",
          unit: "km.",
          type: "range",
          column_name: "dr",
          min: 0.2,
          max: 16.9,
          value: [0.2, 16.9],
          subcategory: "accessibility",
        },
        {
          name: "Average Distance to Towns",
          unit: "km.",
          type: "range",
          column_name: "dt",
          min: 0,
          max: 47.4,
          value: [0, 47.4],
          subcategory: "accessibility",
        },
        {
          name: "Average Diahrrea Prevalence in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "dia",
          min: 2.5,
          max: 5.2,
          value: [2.5, 5.5],
          subcategory: "health",
        },
        {
          name: "Average Predicted Annual Cholera Incidence",
          unit: "cases/100,000pp",
          type: "range",
          column_name: "cholera",
          min: 0.1,
          max: 898.2,
          value: [0.1, 898.2],
          subcategory: "health",
        },
        {
          name: "Average Mortality in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "u5m",
          min: 4.6,
          max: 7.5,
          value: [4.6, 7.5],
          subcategory: "health",
        },
        {
          name: "Average Women's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_w",
          min: 3,
          max: 10,
          value: [3, 10],
          subcategory: "socioeconomic",
        },
        {
          name: "Average Men's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_m",
          min: 4,
          max: 11,
          value: [4, 11],
          subcategory: "socioeconomic",
        },
        {
          name: "Average Relative Wealth Index",
          unit: "index",
          type: "range_non_linear",
          column_name: "rwi",
          scaledMin: -0.53,
          scaledMax: 1.35,
          scaledValue: [-0.53, 1.35],
          subcategory: "socioeconomic",
          min: 0,
          max: 60,
          value: [0, 60], //the actual min/max of column
          marks: [
            {
              value: 0,
              scaledValue: -0.53,
              label: "-0.53",
            },
            {
              value: 10,
              scaledValue: -0.25,
              label: "-0.25",
            },
            {
              value: 20,
              scaledValue: 0,
              label: "0",
            },
            {
              value: 30,
              scaledValue: 0.25,
              label: "0.25",
            },
            {
              value: 40,
              scaledValue: 0.6,
              label: "0.6",
            },
            {
              value: 50,
              scaledValue: 1,
              label: "1",
            },
            {
              value: 60,
              scaledValue: 1.4,
              label: "1.4",
            },
          ],
        },
        {
          name: "Rural Remote",
          unit: "%",
          type: "none",
          column_name: "rr",
          subcategory: "accessibility",
        },
        {
          name: "Rural On-road",
          unit: "%",
          type: "none",
          column_name: "rrd",
          subcategory: "accessibility",
        },
        {
          name: "Rural Mixed",
          unit: "%",
          type: "none",
          column_name: "rm",
          subcategory: "accessibility",
        },
        {
          name: "Urban",
          unit: "%",
          type: "none",
          column_name: "u",
          subcategory: "accessibility",
        },
        {
          name: "Region",
          type: "none",
          column_name: "name_1",
          subcategory: "id",
        },
        {
          name: "District",
          type: "none",
          column_name: "name_2",
          subcategory: "id",
        },
      ],
    },
    {
      name: "Estimated settlement",
      carto_tableName: "gha_multivariable_comms",
      carto_layer: null /* we will insert carto's layer object here */,
      carto_source: null,
      // carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 1;line-color: #000000;line-opacity: 1;}`,
      carto_style: `#layer {polygon-fill: #826dba; polygon-opacity: 0;} #layer::outline {line-width: 1; line-color: #000000; line-opacity: 1;}`,
      accessCounter: new Set(null),
      washCounter: new Set(null),
      socioCounter: new Set(null),
      healthCounter: new Set(null),
      visible: false,
      filters: [
        {
          name: "Rural Typology",
          unit: "",
          type: "categorical",
          column_name: "classes",
          subcategory: "accessibility",
          value: [
            {
              name: "Rural Remote",
              value: 1,
              checked: true,
            },
            {
              name: "Rural On-road",
              value: 2,
              checked: true,
            },
            {
              name: "Rural Mixed",
              value: 3,
              checked: true,
            },
            {
              name: "Urban",
              value: 4,
              checked: true,
            },
          ] /* declaure col values that should be filtered on */,
        },
        {
          name: "Population Estimate",
          unit: "people",
          type: "range_non_linear",
          column_name: "pop",
          min: 0,
          max: 70, //we want 7 breaks not counting start value of 0.
          value: [0, 70], //slider range will be from 0-70, which we will scale to
          scaledMin: 0,
          scaledMax: 5722595,
          scaledValue: [0, 5722595], //the actual min/max of column
          subcategory: "socioeconomic",
          // define 7+1 non linear marks here, note that value goes from 0-70 only
          marks: [
            {
              value: 0,
              scaledValue: 0,
              label: "0",
            },
            {
              value: 10,
              scaledValue: 500,
              label: "500",
            },
            {
              value: 20,
              scaledValue: 1000,
              label: "1K",
            },
            {
              value: 30,
              scaledValue: 5000,
              label: "5K",
            },
            {
              value: 40,
              scaledValue: 50000,
              label: "50K",
            },
            {
              value: 50,
              scaledValue: 100000,
              label: "100K",
            },
            {
              value: 60,
              scaledValue: 1000000,
              label: "1M",
            },
            {
              value: 70,
              scaledValue: 6000000,
              label: "6M",
            },
          ],
        },
        {
          name: "Population Practicing Open Defecation",
          unit: "%",
          type: "range",
          column_name: "od",
          min: 0,
          max: 100,
          value: [0, 100],
          subcategory: "wash",
        },
        {
          name: "Reliance on Unimproved Sanitation",
          unit: "%",
          type: "range",
          column_name: "s_unimp",
          min: 0,
          max: 97,
          value: [0, 97],
          subcategory: "wash",
        },
        {
          name: "Reliance on Unimproved Drinking Water",
          unit: "%",
          type: "range",
          column_name: "w_unimp",
          min: 0,
          max: 80,
          value: [0, 80],
          subcategory: "wash",
        },
        {
          name: "Travel Time to Cities",
          unit: "min.",
          type: "range",
          column_name: "timecities",
          min: 0,
          max: 546,
          value: [0, 546],
          subcategory: "accessibility",
        },
        {
          name: "Distance to Roads",
          unit: "km.",
          type: "range",
          column_name: "dr",
          min: 0,
          max: 37.1,
          value: [0, 37.1],
          subcategory: "accessibility",
        },
        {
          name: "Distance to Towns",
          unit: "km.",
          type: "range",
          column_name: "dt",
          min: 0,
          max: 76.2,
          value: [0, 76.2],
          subcategory: "accessibility",
        },
        {
          name: "Diahrrea Prevalence in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "dia",
          min: 2.3,
          max: 6.7,
          value: [2.3, 6.7],
          subcategory: "health",
        },
        {
          name: "Predicted Annual Cholera Incidence",
          unit: "cases/100,000pp",
          type: "range",
          column_name: "cholera",
          min: 0,
          max: 6410.7,
          value: [0, 6410.7],
          subcategory: "health",
        },
        {
          name: "Mortality in Children <5 Years",
          unit: "%",
          type: "range",
          column_name: "u5m",
          min: 4.3,
          max: 12.7,
          value: [4.3, 12.7],
          subcategory: "health",
        },
        {
          name: "Women's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_w",
          min: 1,
          max: 10,
          value: [1, 10],
          subcategory: "socioeconomic",
        },
        {
          name: "Men's Educational Attainment",
          unit: "yrs.",
          type: "range",
          column_name: "edu_m",
          min: 3,
          max: 11,
          value: [3, 11],
          subcategory: "socioeconomic",
        },
        {
          name: "Rural Remote",
          unit: "%",
          type: "none",
          column_name: "rr",
          subcategory: "accessibility",
        },
        {
          name: "Rural On-road",
          unit: "%",
          type: "none",
          column_name: "rrd",
          subcategory: "accessibility",
        },
        {
          name: "Rural Mixed",
          unit: "%",
          type: "none",
          column_name: "rm",
          subcategory: "accessibility",
        },
        {
          name: "Urban",
          unit: "%",
          type: "none",
          column_name: "u",
          subcategory: "accessibility",
        },
        {
          name: "Region",
          type: "none",
          column_name: "name_1",
          subcategory: "id",
        },
        {
          name: "District",
          type: "none",
          column_name: "name_2",
          subcategory: "id",
        },
      ],
    },
    // {
    //   name: "Limited Estimated settlement",
    //   carto_tableName: "gha_multivariable_comms",
    //   carto_layer: null /* we will insert carto's layer object here */,
    //   carto_source: null,
    //   carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 1;line-color: #000000;line-opacity: 1;}`,
    //   // carto_style: `#layer {polygon-fill: #826dba; polygon-opacity: 0;} #layer::outline {line-width: 1.75; line-color: #000000; line-opacity: 1;}`,
    //   accessCounter: new Set(null),
    //   washCounter: new Set(null),
    //   socioCounter: new Set(null),
    //   healthCounter: new Set(null),
    //   visible: false,
    //   filters: [
    //     {
    //       name: "Rural Typology",
    //       unit: "",
    //       type: "categorical",
    //       column_name: "classes",
    //       subcategory: "accessibility",
    //       value: [
    //         {
    //           name: "Rural Remote",
    //           value: 1,
    //           checked: true,
    //         },
    //         {
    //           name: "Rural On-road",
    //           value: 2,
    //           checked: true,
    //         },
    //         {
    //           name: "Rural Mixed",
    //           value: 3,
    //           checked: true,
    //         },
    //         {
    //           name: "Urban",
    //           value: 4,
    //           checked: true,
    //         },
    //       ] /* declaure col values that should be filtered on */,
    //     },
    //     {
    //       name: "Population Estimate",
    //       unit: "people",
    //       type: "range_non_linear",
    //       column_name: "pop",
    //       min: 0,
    //       max: 70, //we want 7 breaks not counting start value of 0.
    //       value: [0, 70], //slider range will be from 0-70, which we will scale to
    //       scaledMin: 0,
    //       scaledMax: 5722595,
    //       scaledValue: [0, 5722595], //the actual min/max of column
    //       subcategory: "socioeconomic",
    //       // define 7+1 non linear marks here, note that value goes from 0-70 only
    //       marks: [
    //         {
    //           value: 0,
    //           scaledValue: 0,
    //           label: "0",
    //         },
    //         {
    //           value: 10,
    //           scaledValue: 500,
    //           label: "500",
    //         },
    //         {
    //           value: 20,
    //           scaledValue: 1000,
    //           label: "1K",
    //         },
    //         {
    //           value: 30,
    //           scaledValue: 5000,
    //           label: "5K",
    //         },
    //         {
    //           value: 40,
    //           scaledValue: 50000,
    //           label: "50K",
    //         },
    //         {
    //           value: 50,
    //           scaledValue: 100000,
    //           label: "100K",
    //         },
    //         {
    //           value: 60,
    //           scaledValue: 1000000,
    //           label: "1M",
    //         },
    //         {
    //           value: 70,
    //           scaledValue: 6000000,
    //           label: "6M",
    //         },
    //       ],
    //     },
    //     {
    //       name: "Population Practicing Open Defecation",
    //       unit: "%",
    //       type: "",
    //       column_name: "od",
    //       min: 0,
    //       max: 100,
    //       value: [0, 100],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Reliance on Unimproved Sanitation",
    //       unit: "%",
    //       type: "",
    //       column_name: "s_unimp",
    //       min: 0,
    //       max: 97,
    //       value: [0, 97],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Reliance on Unimproved Drinking Water",
    //       unit: "%",
    //       type: "",
    //       column_name: "w_unimp",
    //       min: 0,
    //       max: 80,
    //       value: [0, 80],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Travel Time to Cities",
    //       unit: "min.",
    //       type: "range",
    //       column_name: "timecities",
    //       min: 0,
    //       max: 546,
    //       value: [0, 546],
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Distance to Roads",
    //       unit: "km.",
    //       type: "range",
    //       column_name: "dr",
    //       min: 0,
    //       max: 37.1,
    //       value: [0, 37.1],
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Distance to Towns",
    //       unit: "km.",
    //       type: "range",
    //       column_name: "dt",
    //       min: 0,
    //       max: 76.2,
    //       value: [0, 76.2],
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Diahrrea Prevalence in Children <5 Years",
    //       unit: "%",
    //       type: "",
    //       column_name: "dia",
    //       min: 2.3,
    //       max: 6.7,
    //       value: [2.3, 6.7],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Predicted Annual Cholera Incidence",
    //       unit: "cases/100,000pp",
    //       type: "",
    //       column_name: "cholera",
    //       min: 0,
    //       max: 6410.7,
    //       value: [0, 6410.7],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Mortality in Children <5 Years",
    //       unit: "%",
    //       type: "",
    //       column_name: "u5m",
    //       min: 4.3,
    //       max: 12.7,
    //       value: [4.3, 12.7],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Women's Educational Attainment",
    //       unit: "yrs.",
    //       type: "",
    //       column_name: "edu_w",
    //       min: 1,
    //       max: 10,
    //       value: [1, 10],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Men's Educational Attainment",
    //       unit: "yrs.",
    //       type: "",
    //       column_name: "edu_m",
    //       min: 3,
    //       max: 11,
    //       value: [3, 11],
    //       subcategory: "",
    //     },
    //     {
    //       name: "Rural Remote",
    //       unit: "%",
    //       type: "none",
    //       column_name: "rr",
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Rural On-road",
    //       unit: "%",
    //       type: "none",
    //       column_name: "rrd",
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Rural Mixed",
    //       unit: "%",
    //       type: "none",
    //       column_name: "rm",
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Urban",
    //       unit: "%",
    //       type: "none",
    //       column_name: "u",
    //       subcategory: "accessibility",
    //     },
    //     {
    //       name: "Region",
    //       type: "none",
    //       column_name: "name_1",
    //       subcategory: "id",
    //     },
    //     {
    //       name: "District",
    //       type: "none",
    //       column_name: "name_2",
    //       subcategory: "id",
    //     },
    //   ],
    // },
  ],
};
