export const kenya = {
    name: "Kenya",
    mapID: "kenya",
    lat: -0.0236,
    long: 37.9062,
    zoom: 7,
    /* 
      you can add as many layers for each indicator. 
      do maintain the same structure for all. 
      */
    layers: [
      {
        name: "Country Border",
        carto_tableName: "ken_adm0",
        carto_layer: null /* we will insert carto's layer object here */,
        carto_style: `#layer {polygon-fill: #826dba; polygon-opacity: 0;} #layer::outline {line-width: 1.75; line-color: #000000; line-opacity: 1;}`,
        visible: true,
        filters: [],
      },
      {
        name: "1x1km area",
        carto_tableName: "ken_class",
        carto_source: null,
        carto_layer: null /* we will insert carto's layer object here */,
        carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 0;line-color: #ffffff;line-opacity: 0;}`,
        visible: false,
        accessCounter: new Set(null),
        washCounter: new Set(null),
        socioCounter: new Set(null),
        healthCounter: new Set(null),
        filters: [
          {
            name: "Rural Typology",
            unit: "",
            type: "categorical",
            column_name: "classes",
            subcategory: "accessibility",
            value: [
              {
                name: "Rural Remote",
                value: 1,
                checked: true,
              },
              {
                name: "Rural On-road",
                value: 2,
                checked: true,
              },
              {
                name: "Rural Mixed",
                value: 3,
                checked: true,
              },
              {
                name: "Urban",
                value: 4,
                checked: true,
              },
            ],
          },
        ],
      },
      {
        name: "5x5km area",
        carto_tableName: "ken_multivariable_pixel",
        carto_source: null,
        carto_layer: null,
        carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 0;line-color: #ffffff;line-opacity: 0;}`,
        visible: true,
        accessCounter: new Set(null),
        washCounter: new Set(null),
        socioCounter: new Set(null),
        healthCounter: new Set(null),
        filters: [
          {
            name: "Rural Typology",
            unit: "",
            type: "categorical",
            column_name: "classes",
            subcategory: "accessibility",
            value: [
              {
                name: "Rural Remote",
                value: 1,
                checked: true,
              },
              {
                name: "Rural On-road",
                value: 2,
                checked: true,
              },
              {
                name: "Rural Mixed",
                value: 3,
                checked: true,
              },
              {
                name: "Urban",
                value: 4,
                checked: true,
              },
            ] /* declaure col values that should be filtered on */,
          },
          {
            name: "Population Practicing Open Defecation",
            unit: "%",
            type: "range",
            column_name: "od",
            min: 0,
            max: 99,
            value: [0, 99],
            subcategory: "wash",
          },
          {
            name: "Travel Time to Cities",
            unit: "min.",
            type: "range",
            column_name: "timecities",
            min: 0,
            max: 1053,
            value: [0, 1053],
            subcategory: "accessibility",
          },
          {
            name: "Diahrrea Prevalence in Children <5 Years",
            unit: "%",
            type: "range",
            column_name: "dia",
            min: 1.9,
            max: 6.6,
            value: [1.9, 6.6],
            subcategory: "health",
          },
          {
            name: "Predicted Annual Cholera Incidence",
            unit: "cases/100,000pp",
            type: "range",
            column_name: "cholera",
            min: 0,
            max: 3141.9,
            value: [0, 3141.9],
            subcategory: "health",
          },
          {
            name: "Reliance on Unimproved Sanitation",
            unit: "%",
            type: "range",
            column_name: "s_unimp",
            min: 0,
            max: 99,
            value: [0, 99],
            subcategory: "wash",
          },
          {
            name: "Reliance on Unimproved Drinking Water",
            unit: "%",
            type: "range",
            column_name: "w_unimp",
            min: 0,
            max: 98,
            value: [0, 98],
            subcategory: "wash",
          },
          {
            name: "Women's Educational Attainment",
            unit: "yrs.",
            type: "range",
            column_name: "edu_w",
            min: 0,
            max: 12,
            value: [0, 12],
            subcategory: "socioeconomic",
          },
          {
            name: "Men's Educational Attainment",
            unit: "yrs.",
            type: "range",
            column_name: "edu_m",
            min: 2,
            max: 12,
            value: [2, 12],
            subcategory: "socioeconomic",
          },
          {
            name: "Mortality in Children <5 Years",
            unit: "%",
            type: "range",
            column_name: "u5m",
            min: 2.2,
            max: 9.5,
            value: [2.2, 9.5],
            subcategory: "health",
          },
          {
            name: "Distance to Roads",
            unit: "km.",
            type: "range",
            column_name: "dr",
            min: 0.1,
            max: 65.5,
            value: [0.1, 65.5],
            subcategory: "accessibility",
          },
          {
            name: "Distance to Towns",
            unit: "km.",
            type: "range",
            column_name: "dt",
            min: 0,
            max: 185.6,
            value: [0, 185.6],
            subcategory: "accessibility",
          },
          {
            name: "Population Estimate",
            unit: "people",
            type: "range_non_linear",
            column_name: "pop",
            min: 0,
            max: 70, //we want 7 breaks not counting start value of 0.
            value: [0, 70], //slider range will be from 0-70, which we will scale to
            scaledMin: 0,
            scaledMax: 696219,
            scaledValue: [0, 696219], //the actual min/max of column
            subcategory: "socioeconomic",
            // define 7+1 non linear marks here, note that value goes from 0-70 only
            marks: [
              {
                value: 0,
                scaledValue: 0,
                label: "0",
              },
              {
                value: 10,
                scaledValue: 100,
                label: "100",
              },
              {
                value: 20,
                scaledValue: 500,
                label: "500",
              },
              {
                value: 30,
                scaledValue: 1000,
                label: "1K",
              },
              {
                value: 40,
                scaledValue: 5000,
                label: "5K",
              },
              {
                value: 50,
                scaledValue: 50000,
                label: "50K",
              },
              {
                value: 60,
                scaledValue: 100000,
                label: "100K",
              },
              {
                value: 70,
                scaledValue: 700000,
                label: "700K",
              },
            ],
          },
          {
            name: "Rural Remote",
            unit: "%",
            type: "none",
            column_name: "rr",
            subcategory: "accessibility",
          },
          {
            name: "Rural On-road",
            unit: "%",
            type: "none",
            column_name: "rrd",
            subcategory: "accessibility",
          },
          {
            name: "Rural Mixed",
            unit: "%",
            type: "none",
            column_name: "rm",
            subcategory: "accessibility",
          },
          {
            name: "Urban",
            unit: "%",
            type: "none",
            column_name: "u",
            subcategory: "accessibility",
          },
          {
            name: "County",
            type: "none",
            column_name: "name_1",
            subcategory: "id",
          },
          {
            name: "Subcounty",
            type: "none",
            column_name: "name_2",
            subcategory: "id",
          },
        ],
      },
      {
        name: "County",
        carto_tableName: "ken_multivariable_dist",
        carto_source: null,
        carto_layer: null,
        carto_style: `#layer {polygon-fill: ramp([classes], (#3d4bc7, #4f9130, #bf4343, #c49755), (1, 2, 3, 4), '=', category);} #layer::outline {line-width: 1;line-color: #000000;line-opacity: 1;}`,
        visible: false,
        accessCounter: new Set(null),
        washCounter: new Set(null),
        socioCounter: new Set(null),
        healthCounter: new Set(null),
        filters: [
          {
            name: "Predominant Rural Typology",
            unit: "",
            type: "categorical",
            column_name: "classes",
            value: [
              {
                name: "Predominantly Rural Remote",
                value: 1,
                checked: true,
              },
              {
                name: "Predominantly Rural on-road",
                value: 2,
                checked: true,
              },
              {
                name: "Predominantly Rural Mixed",
                value: 3,
                checked: true,
              },
              {
                name: "Predominantly Urban",
                value: 4,
                checked: true,
              },
            ] /* declaure col values that should be filtered on */,
            subcategory: "accessibility",
          },
          {
            name: "Average Population Practicing Open Defecation",
            unit: "%",
            type: "range",
            column_name: "od",
            min: 10,
            max: 60,
            value: [10, 60],
            subcategory: "wash",
          },
          {
            name: "Average Travel Time to Cities",
            unit: "min.",
            type: "range",
            column_name: "timecities",
            min: 0,
            max: 490,
            value: [0, 490],
            subcategory: "accessibility",
          },
          {
            name: "Average Diahrrea Prevalence in Children <5 Years",
            unit: "%",
            type: "range",
            column_name: "dia",
            min: 2,
            max: 4.7,
            value: [2, 4.7],
            subcategory: "health",
          },
          {
            name: "Average Predicted Annual Cholera Incidence",
            unit: "cases/100,000pp",
            type: "range",
            column_name: "cholera",
            min: 0,
            max: 370.3,
            value: [0, 370.3],
            subcategory: "health",
          },
          {
            name: "Average Reliance on Unimproved Sanitation",
            unit: "%",
            type: "range",
            column_name: "s_unimp",
            min: 11,
            max: 67,
            value: [11, 67],
            subcategory: "wash",
          },
          {
            name: "Average Reliance on Unimproved Drinking Water",
            unit: "%",
            type: "range",
            column_name: "w_unimp",
            min: 0,
            max: 47,
            value: [0, 47],
            subcategory: "wash",
          },
          {
            name: "Average Women's Educational Attainment",
            unit: "yrs.",
            type: "range",
            column_name: "edu_w",
            min: 1,
            max: 11,
            value: [1, 11],
            subcategory: "socioeconomic",
          },
          {
            name: "Average Men's Educational Attainment",
            unit: "yrs.",
            type: "range",
            column_name: "edu_m",
            min: 3,
            max: 12,
            value: [3, 12],
            subcategory: "socioeconomic",
          },
          {
            name: "Average Mortality in Children <5 Years",
            unit: "%",
            type: "range",
            column_name: "u5m",
            min: 2.6,
            max: 8.4,
            value: [2.6, 8.4],
            subcategory: "health",
          },
          {
            name: "Average Distance to Roads",
            unit: "km.",
            type: "range",
            column_name: "dr",
            min: 0.1,
            max: 36.4,
            value: [0.1, 36.4],
            subcategory: "accessibility",
          },
          {
            name: "Average Distance to Towns",
            unit: "km.",
            type: "range",
            column_name: "dt",
            min: 0,
            max: 97.7,
            value: [0, 97.7],
            subcategory: "accessibility",
          },
          {
            name: "Population Estimate",
            unit: "people",
            type: "range",
            column_name: "pop",
            min: 17295,
            max: 670200,
            value: [17295, 670200],
            subcategory: "socioeconomic",
          },
          // {
          //   name: "Average Relative Wealth Index",
          //   unit: "index",
          //   type: "range_non_linear",
          //   column_name: "rwi",
          //   scaledMin: -0.53,
          //   scaledMax: 1.35,
          //   scaledValue: [-0.53, 1.35],
          //   subcategory: "socioeconomic",
          //   min: 0,
          //   max: 60,
          //   value: [0, 60], //the actual min/max of column
          //   marks: [
          //     {
          //       value: 0,
          //       scaledValue: -0.53,
          //       label: "-0.53",
          //     },
          //     {
          //       value: 10,
          //       scaledValue: -0.25,
          //       label: "-0.25",
          //     },
          //     {
          //       value: 20,
          //       scaledValue: 0,
          //       label: "0",
          //     },
          //     {
          //       value: 30,
          //       scaledValue: 0.25,
          //       label: "0.25",
          //     },
          //     {
          //       value: 40,
          //       scaledValue: 0.6,
          //       label: "0.6",
          //     },
          //     {
          //       value: 50,
          //       scaledValue: 1,
          //       label: "1",
          //     },
          //     {
          //       value: 60,
          //       scaledValue: 1.4,
          //       label: "1.4",
          //     },
          //   ],
          // },
          {
            name: "Rural Remote",
            unit: "%",
            type: "none",
            column_name: "rr",
            subcategory: "accessibility",
          },
          {
            name: "Rural On-road",
            unit: "%",
            type: "none",
            column_name: "rrd",
            subcategory: "accessibility",
          },
          {
            name: "Rural Mixed",
            unit: "%",
            type: "none",
            column_name: "rm",
            subcategory: "accessibility",
          },
          {
            name: "Urban",
            unit: "%",
            type: "none",
            column_name: "u",
            subcategory: "accessibility",
          },
          {
            name: "County",
            type: "none",
            column_name: "name_1",
            subcategory: "id",
          },
          {
            name: "Subcounty",
            type: "none",
            column_name: "name_2",
            subcategory: "id",
          },
        ],
      },
      {
        name: "Estimated settlement",
        carto_tableName: "ken_multivariable_comms",
        carto_layer: null /* we will insert carto's layer object here */,
        carto_source: null,
        carto_style: `#layer {polygon-fill: #826dba; polygon-opacity: 0;} #layer::outline {line-width: 1; line-color: #000000; line-opacity: 1;}`,
        accessCounter: new Set(null),
        washCounter: new Set(null),
        socioCounter: new Set(null),
        healthCounter: new Set(null),
        visible: false,
        filters: [
          {
            name: "Rural Typology",
            unit: "",
            type: "categorical",
            column_name: "classes",
            subcategory: "accessibility",
            value: [
              {
                name: "Rural Remote",
                value: 1,
                checked: true,
              },
              {
                name: "Rural On-road",
                value: 2,
                checked: true,
              },
              {
                name: "Rural Mixed",
                value: 3,
                checked: true,
              },
              {
                name: "Urban",
                value: 4,
                checked: true,
              },
            ] /* declaure col values that should be filtered on */,
          },
          {
            name: "Travel Time to Cities",
            unit: "min.",
            type: "range",
            column_name: "timecities",
            min: 0,
            max: 923,
            value: [0, 923],
            subcategory: "accessibility",
          },
          {
            name: "Distance to Roads",
            unit: "km.",
            type: "range",
            column_name: "dr",
            min: 0,
            max: 65.5,
            value: [0, 65.5],
            subcategory: "accessibility",
          },
          {
            name: "Distance to Towns",
            unit: "km.",
            type: "range",
            column_name: "dt",
            min: 0,
            max: 177.6,
            value: [0, 177.6],
            subcategory: "accessibility",
          },
          {
            name: "Population Estimate",
            unit: "people",
            type: "range_non_linear",
            column_name: "pop",
            min: 0,
            max: 70, //we want 7 breaks not counting start value of 0.
            value: [0, 70], //slider range will be from 0-70, which we will scale to
            scaledMin: 0,
            scaledMax: 7572461,
            scaledValue: [0, 7572461], //the actual min/max of column
            subcategory: "socioeconomic",
            // define 7+1 non linear marks here, note that value goes from 0-70 only
            marks: [
              {
                value: 0,
                scaledValue: 0,
                label: "0",
              },
              {
                value: 10,
                scaledValue: 500,
                label: "500",
              },
              {
                value: 20,
                scaledValue: 1000,
                label: "1K",
              },
              {
                value: 30,
                scaledValue: 5000,
                label: "5K",
              },
              {
                value: 40,
                scaledValue: 50000,
                label: "50K",
              },
              {
                value: 50,
                scaledValue: 100000,
                label: "100K",
              },
              {
                value: 60,
                scaledValue: 1000000,
                label: "1M",
              },
              {
                value: 70,
                scaledValue: 7600000,
                label: "7.6M",
              },
            ],
          },
          {
            name: "Rural Remote",
            unit: "%",
            type: "none",
            column_name: "rr",
            subcategory: "accessibility",
          },
          {
            name: "Rural On-road",
            unit: "%",
            type: "none",
            column_name: "rrd",
            subcategory: "accessibility",
          },
          {
            name: "Rural Mixed",
            unit: "%",
            type: "none",
            column_name: "rm",
            subcategory: "accessibility",
          },
          {
            name: "Urban",
            unit: "%",
            type: "none",
            column_name: "u",
            subcategory: "accessibility",
          },
          {
            name: "County",
            type: "none",
            column_name: "name_1",
            subcategory: "id",
          },
          {
            name: "Subcounty",
            type: "none",
            column_name: "name_2",
            subcategory: "id",
          },
        ],
      },
    ],
  };
  